// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51JHuuwU2-Vdw0fVeqnKmwpg48W2O-IU',
    appId: '1:951746430119:android:ea3d692643ca236be6c782',
    messagingSenderId: '951746430119',
    projectId: 'aichat-18208',
    storageBucket: 'aichat-18208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2y5i35cqbUquWcB-WvQvSWkaQoHwW98g',
    appId: '1:951746430119:ios:9170f263c28b3aa5e6c782',
    messagingSenderId: '951746430119',
    projectId: 'aichat-18208',
    storageBucket: 'aichat-18208.firebasestorage.app',
    iosBundleId: 'com.example.aiChatapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnQkjzl6EZCZpvcNGzoyWrvav9v2-p3Lk',
    appId: '1:951746430119:web:39ce835a4dc50c00e6c782',
    messagingSenderId: '951746430119',
    projectId: 'aichat-18208',
    authDomain: 'aichat-18208.firebaseapp.com',
    storageBucket: 'aichat-18208.firebasestorage.app',
    measurementId: 'G-3G4PKP8L62',
  );

}